# Generated by Django 5.2.4 on 2025-07-19 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_remove_lesson_video_link_alter_course_preview_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="paid_at",
            new_name="payment_date",
        ),
        migrations.AddField(
            model_name="payment",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="materials.lesson",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счёт")],
                default="cash",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="course_previews/"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="lesson_previews/"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="materials.course",
            ),
        ),
    ]
