# Generated by Django 5.2.4 on 2025-07-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_remove_course_description_remove_course_preview_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
